export const level1 = [
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XX     XXXXX          XXXXXXXXXXXXXXXXXXXX",
"XXXX                            XXXXXXXXXX",
"XXXXXXXXXXXXXXX         XXXXX      XXXXXXX",
"XXXX               XXXXXXXXXXXX    XXXXXXX",
"XXXX  s         XXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
]