export const level1 = [
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XX     XXXXXXXXXXXX                      X",
"XX          X         XXXXXXXXXXXX       X",
"XXXX               X X          XXXXX   XX",
"XXXXXXXXXXXXXXX         XXXXX      XXXX XX",
"XXXX     XXX       XXXXXXXXXXXX    XXXX XX",
"XXXX  s         XXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
];
export const level2 = [
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XX                                                        XXXXXXX",
"XX                                                        XXXXXXX",
"XX           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XX          XXXXXXXXXXXX             XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XX                                                    XXXXXXXXXXX",
"XX                                                    XXXXXXXXXXX",
"XX                                                    XXXXXXXXXXX",
"XX                                                    XXXXXXXXXXX",
"XX    XXXX                                            XXXXXXXXXXX",
"XX                 XXXXXXX                                 XXXXXX",
"XX                                 XXXXXX                  XXXXXX",
"XXXXXXXXXXXXX                                              XXXXXX",
"XXXXXXXXX                                                  XXXXXX",
"XXXXX                                             XXXXXXXXXXXXXXX",
"X                                                    XXXXXXXXXXXX",
"X                                                    XXXXXXXXXXXX",
"X                        XX                 XX       XXXXXXXXXXXX",
"X                        XXXXXXXXXX         XX       XXXXXXXXXXXX",
"X            XX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X  s         XX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXX     XXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXX     XXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
];
export const level2_alt = [
"   ww             wwwwwwwwwww                                 ww ",
"   ww             wwwwwwwwwww              ww                 ww ",
"   ww             wwwwwwwwwww              ww                 ww ",
"   wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww ",
"   wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww ",
"   ww                                      ww                www ",
"wwwww           wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww ",
"wwwww          wwwwwwwwwwwww            wwwwwwwwwwwwwwwwwwwwwwww ",
"wwwww                     ww                       ww    wwwwwww ",
"wwwww                     ww                       ww    wwwwwww ",
"wwwww              wwwwwwwwwwwwwwwwwwwwwwww        ww    wwwwwww ",
"   ww     wwww     wwwwwwwwwwwwwwwwwwwwwwww              wwwwwww ",
"   ww    wwwww            ww                   ww        wwwwwww ",
"   ww     wwww        wwwwwww                  ww             ww ",
"   ww     wwww                        wwwwww   ww             ww ",
"   wwwwwwwwwwwww                               ww             ww ",
"   wwwwwwwwwww            wwwwwww        wwwwwwwwwwwwwwwwwwwwwww ",
"   wwwww  wwww            wwwwwww        wwwwwwwwwwwwwwwwwwwwwww ",
"   w      wwww            ww                   ww       wwwwwwww ",
"   w      wwww            ww                   ww       wwwwwwww ",
"wwww      wwww            wwww                 ww       wwwwwwww ",
"wwww      wwww            wwwwwwwwwwww         ww       wwwwwwww ",
"   w      wwww            wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww ",
"   w      wwwwwwwwwwwwwwwwww                        wwwwwwwwwwww ",
"   wwwwwwwwwwwwwwwwwwwwwwwww                        wwwwwwwwwwww ",
"                          ww                                     ",
"                          ww                                     ",
]
