export const level1 = [
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XX     XXXXXXXXXXXX                      X",
"XX          X         XXXXXXXXXXXX       X",
"XXXX               X X          XXXXX   XX",
"XXXXXXXXXXXXXXX         XXXXX      XXXX XX",
"XXXX     XXX       XXXXXXXXXXXX    XXXX XX",
"XXXX  s         XXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
];
export const level2 = [
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XX                                                        XXXXXXX",
"XX                                                        XXXXXXX",
"XX           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XX          XXXXXXXXXXXX             XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XX                                                    XXXXXXXXXXX",
"XX                                                    XXXXXXXXXXX",
"XX                                                    XXXXXXXXXXX",
"XX                                                    XXXXXXXXXXX",
"XX    XXXX                                            XXXXXXXXXXX",
"XX                 XXXXXXX                                 XXXXXX",
"XX                                 XXXXXX                  XXXXXX",
"XXXXXXXXXXXXX                                              XXXXXX",
"XXXXXXXXX                                                  XXXXXX",
"XXXXX                                             XXXXXXXXXXXXXXX",
"X                                                    XXXXXXXXXXXX",
"X                                                    XXXXXXXXXXXX",
"X                        XX                 XX       XXXXXXXXXXXX",
"X                        XXXXXXXXXX         XX       XXXXXXXXXXXX",
"X            XX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X  s         XX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXX     XXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXX     XXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
];
export const level2_alt = [
"   XX             XXXXXXXXXXX                                 XX ",
"   XX             XXXXXXXXXXX              XX                 XX ",
"   XX             XXXXXXXXXXX              XX                 XX ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ",
"   XX                                      XX                XXX ",
"XXXXX           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ",
"XXXXX          XXXXXXXXXXXXX            XXXXXXXXXXXXXXXXXXXXXXXX ",
"XXXXX                     XX                       XX    XXXXXXX ",
"XXXXX                     XX                       XX    XXXXXXX ",
"XXXXX              XXXXXXXXXXXXXXXXXXXXXXXX        XX    XXXXXXX ",
"   XX     XXXX     XXXXXXXXXXXXXXXXXXXXXXXX              XXXXXXX ",
"   XX    XXXXX            XX                   XX        XXXXXXX ",
"   XX     XXXX        XXXXXXX                  XX             XX ",
"   XX     XXXX                        XXXXXX   XX             XX ",
"   XXXXXXXXXXXXX                               XX             XX ",
"   XXXXXXXXXXX            XXXXXXX        XXXXXXXXXXXXXXXXXXXXXXX ",
"   XXXXX  XXXX            XXXXXXX        XXXXXXXXXXXXXXXXXXXXXXX ",
"   X      XXXX            XX                   XX       XXXXXXXX ",
"   X      XXXX            XX                   XX       XXXXXXXX ",
"XXXX      XXXX            XXXX                 XX       XXXXXXXX ",
"XXXX      XXXX            XXXXXXXXXXXX         XX       XXXXXXXX ",
"   X      XXXX            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ",
"   X  s   XXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXX ",
"   XXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXX ",
"                          XX                                     ",
"                          XX                                     ",
]
